[build]
publish = "_site"
command = "npm run build"

[build.environment]
NODE_VERSION = "24.14.0"
NPM_VERSION = "11.9.0"

[context.deploy-preview]
command = "SITE_URL=$DEPLOY_PRIME_URL npm run build"
